name: Keycloak Quickstarts CI

on: [push, pull_request]

jobs:
  build:
    name: Run server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: ['group1', 'group2', 'group3', 'group4', 'group5', 'group6', 'group7']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run server
        run: |
          ./travis-server.sh
          ./scripts/generate_keycloak_json.sh

      - name: Compile
        run: |
          mvn -s maven-settings.xml clean install --no-snapshot-updates -B -V -q
          mvn -s maven-settings.xml -Padd-datasource install -Djboss.server.port=10090 -f user-storage-jpa -q

      - name: Tests
        run: ./travis-run-tests.sh ${{ matrix.group }}

